### ISSUE TITLE
Bounty Completion Not Registering

### ISSUE THREAD

**Issue by MrBojangl3s** [RandyKnapp/ValheimMods#284]
Tested in both singleplayer and multiplayer.
In Singleplayer, I don't get "VANQUISHED" after killing the bounty target **_and_** the minions. So I have to abandon bounties as they don't complete.

In **_Multiplayer_**, I have had success with bounties completing if I am not the host of the server. If I join my friend's game (we both have the Epic Loot mod with the same configured options), I can complete bounties but he can't.

It seems as if the player is the host of the server (which would make sense in single player as that is basically a solo-hosted server) they cannot complete bounties, but other players can if they are not hosting.

Overall, it seems that across multiple mod setups and multiple configurations, **players are having issues with the registration of the kill of the bounty target.** 
![image](https://user-images.githubusercontent.com/86940038/124417957-f0496a80-dd1f-11eb-82d7-e7cc896c5fa8.png)

**Comment by Mewthulhu** [comment]
I just wanted to say, experiencing the same as above- no ability to complete bounties, no verification of target in a multiplayer dedicated game.

Additional killings of minions do not yield this. Server restarts attempted, a few values tweaked in other solutions and nothing. No 'Vanquished' notifications pop up and the red circles remain.

**Comment by SuntooX** [comment]
Can confirm, replicated on clean install; probably should have flushed my config files as well though, so might still be a compatibility issue (for me anyways)?

**Comment by awebbdev** [comment]
I can confirm this is an actual bug in the code.  I'm working on a fix for this, but as I have not yet contributed to this project I am not sure it will be accepted.

**Comment by Mewthulhu** [comment]
> I can confirm this is an actual bug in the code. I'm working on a fix for this, but as I have not yet contributed to this project I am not sure it will be accepted.

I'd love if you could make a temporary patch-mod for this, even without approval! Please do reply in this thread if you do, as I love this mod dearly and bounties add so much flavour to my game. We've actually paused play on our server til it's fixed!

**Comment by RandyKnapp** [comment]
@awebbdev I really appreciate you figuring this out, I've been very busy lately. If you find a fix, please please make a Pull Request and I will get it integrated!

**Comment by RandyKnapp** [comment]
@awebbdev Also, what is the bug?

**Comment by awebbdev** [comment]
I'm almost done, just going to test my changes.  I wanted to add a command to "regen" the current bounties, but abandoning is really the only option.  

Commit 442ca54a in the BountyTarget class - Initialize and Reinitialize functions - introduced a logic check on if the instance was a server and was dedicated or wasn't a server and not dedicated.  When I ran some debug logging right before that check  my single player game was a server, but not dedicated.  Inside the if statement the ToPackage is called setting the _bountyInfo property.  This is then used in the OnDeath() resulting in a null reference when that is run.

Simplest fix was to remove that logic check introduced and I had zero issues after, I'm trying to make it so, that the InvokeRoutedRPC function can accept a null ZPackage and function correctly.  Just need to try out as many scenarios as I have time for today.

**Comment by awebbdev** [comment]
Just submitted the PR, I added a check that should allow for any existing Bounties where the target hasn't been killed to now work properly.

**Comment by Digitalroot** [comment]
Using the current version of the EL code base. #288 I get the following when killing a bounty target. 

I get this error running the game SP, no server started or SP with server started from the client.

```
[Error  : Unity Log] EndOfStreamException: Unable to read beyond the end of the stream.
Stack trace:
System.IO.__Error.EndOfFile () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.BinaryReader.ReadByte () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.BinaryReader.Read7BitEncodedInt () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.BinaryReader.ReadString () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
ZPackage.ReadString () (at <1b865f8b3455488592cdc401081112e3>:0)
ZRpc.Deserialize (System.Reflection.ParameterInfo[] paramInfo, ZPackage pkg, System.Collections.Generic.List`1[System.Object]& parameters) (at <1b865f8b3455488592cdc401081112e3>:0)
ZNetView.Deserialize (System.Int64 callerID, System.Reflection.ParameterInfo[] paramInfo, ZPackage pkg) (at <1b865f8b3455488592cdc401081112e3>:0)
RoutedMethod`3[T,U,V].Invoke (System.Int64 rpc, ZPackage pkg) (at <1b865f8b3455488592cdc401081112e3>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <1b865f8b3455488592cdc401081112e3>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <1b865f8b3455488592cdc401081112e3>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, System.String methodName, System.Object[] parameters) (at <1b865f8b3455488592cdc401081112e3>:0)
ZRoutedRpc.InvokeRoutedRPC (System.String methodName, System.Object[] parameters) (at <1b865f8b3455488592cdc401081112e3>:0)
EpicLoot.Adventure.BountyTarget.OnDeath () (at <65777a7da40745f99767f4dec0233ae8>:0)
(wrapper dynamic-method) Character.DMD<Character::CheckDeath>(Character)
(wrapper dynamic-method) Character.DMD<Character::FixedUpdate>(Character)
Humanoid.FixedUpdate () (at <1b865f8b3455488592cdc401081112e3>:0)
```

Reverting to 0.8.0 returns to a working state.

**Comment by awebbdev** [comment]
I'll try to see if I can replicate that issue and fix that asap. I saw that issue once but had fixed it where it occurred for me.

**Comment by RandyKnapp** [comment]
I have cleaned up the code and made it work for dedicated servers, let me
get it committed. It will be a couple of hours.

**Comment by RandyKnapp** [comment]
Okay, see changes in ddd4198

**Comment by Digitalroot** [comment]
Testing
- [ ] SP
- [ ] SP Client w/ Server enabled

**Comment by RandyKnapp** [comment]
A few other situations to test:
- [ ] MP D. Server - Accept bounty, have another player kill bounty target, see that you completed the bounty.
- [ ] MP D. Server - Accept bounty, logout, have another player kill the bounty target while you're offline, login, see that you completed the bounty.

(I've tested all these with my dedi, but it would be nice to get a confirmation before shipping this).

**Comment by sbtoonz** [comment]
I can run these two test case scenarios tomorrow afternoon with a group of people

**Comment by Digitalroot** [comment]
> I can run these two test case scenarios tomorrow afternoon with a group of people 
> 

Would you cover all 4 MP test cases?

**Comment by sbtoonz** [comment]
I can run all four cases on a remote Linux and remote windows host.

**Comment by Kuraigu242** [comment]
AWESOME MOD RANDY! Thanks so much. I've been following this thread and wanted to say thank you all so much for your time working on this. Valheim is a better game because of this mod.  I been playing 8.0 just so I can run bounties but can't wait until it's all working correctly.  Thanks again.

**Comment by Mewthulhu** [comment]
> I can run all four cases on a remote Linux and remote windows host.

Any luck with these? Thank you so much for helping!~

**Comment by sbtoonz** [comment]
> > I can run all four cases on a remote Linux and remote windows host.
> 
> Any luck with these? Thank you so much for helping!~

if @Digitalroot  has some time this afternoon to be the other human needed I can do this today, Ill get a hold of him on discord when he wakes up

**Comment by Digitalroot** [comment]
> 
> 
> > > I can run all four cases on a remote Linux and remote windows host.
> > 
> > 
> > Any luck with these? Thank you so much for helping!~
> 
> if @Digitalroot has some time this afternoon to be the other human needed I can do this today, Ill get a hold of him on discord when he wakes up

I will not be around until late!

**Comment by Mewthulhu** [comment]
> > > I can run all four cases on a remote Linux and remote windows host.
> > 
> > 
> > Any luck with these? Thank you so much for helping!~
> 
> if @Digitalroot has some time this afternoon to be the other human needed I can do this today, Ill get a hold of him on discord when he wakes up

I can jump on and help? I am supposedly a hooman :D 

Mewthulhu#4077 on discord.

**Comment by Kuraigu242** [comment]
Hey guys. First off, thanks again for taking time to do what has been done. But also, have there been any conclusions to the testing and issues resolved? There hasn't been any comments in awhile.  Been hoping each day I log in that the problem has been corrected.  And thanks again and hope  Hearth n Home is released soon.

**Comment by Digitalroot** [comment]
Let me track down someone and get the MP tested

**Comment by RandyKnapp** [comment]
I actually think it's good to go, I've tested the MP issues (I have two
steam accounts for testing), but with an issue this hairy I was hoping for
others to confirm.

+R

**Comment by Digitalroot** [comment]
I am doing so now

**Comment by Geoffro1611** [comment]
I don't know if this will be a help or a hindrance but I'm getting this code when entering the search area for Ithturus the Terrible. I have also had similar instances on other bounties where the target simply doesn't appear.
![EL Error](https://user-images.githubusercontent.com/88099532/127345059-bc4e29b6-4a03-48c8-83b9-8138aa9adac5.jpg)

**Comment by Geoffro1611** [comment]
Great work, love this mod

**Comment by sbtoonz** [comment]
Sorry about lack of reply/testing had to deal with some AC issues at the house and it just got replaced.
Looks like testing was completed and all cases validated 

Looking forward to next release

**Comment by RandyKnapp** [comment]
Should be fixed in 0.8.3

**Comment by Mewthulhu** [comment]
Unfortunately, we've had persisting issues with this on our server I'm afraid...

**Comment by Digitalroot** [comment]
> Unfortunately, we've had persisting issues with this on our server I'm afraid... 

Try updating to 0.8.4

**Comment by Mewthulhu** [comment]
Tried checking and double checking, unfortunately they simply still won't
clear existing ones or complete new ones :/ I'm afraid I can't offer more
help beyond that, as I'm not too tech savvy. Might just be a weird unique
case though.

**Comment by KuuYami** [comment]
It seems this was resolved for some people. I'm still having this issue on my friend's server. As far as I'm aware we are running the newest version of the mod, since it was only installed a few days ago.

**Comment by darksinthe** [comment]
having the same issue with 0.8.7 . anyone have a fix?

**Comment by wavespringer** [comment]
oof.  Why am I here in 2025 with the same issue :(.

- Only running EpicLoot mod on Dedicated Server
- All EpicLoot files in EpicLoot folder in plugins
- EpicLoot Installed on local client
- Cannot claim bounties.

Is the BountySaves folder still being used in EpicLoot folder contained in the config folder?
I'm not seeing any files written here.
